### ISSUE TITLE
Can create support async operations?

### ISSUE THREAD

**Issue by toranb** [miguelcobain/ember-selectize#11]
For example, my create method kicks off a promise that isn't resolved right away. Could we make the create respect async code like this by waiting for the promise to resolve?

**Comment by miguelcobain** [comment]
But what is really your problem?
ember-selectize will update the selectize instance whenever the selection or content changes. Why do you need to wait? What for?

**Comment by toranb** [comment]
When I'm using ember-data it requires me to pushObject 2x (the first time it happens my store shows it (and the drop down), yet i need to pushObject again for it to set this item as the currently selected item). If I pushObject 2x I end up with 2 objects in memory w/ the same attributes /etc.

I've spent a good part of the day trying to track down the exact issue. It seems when I pushObject 2x the _onItemAdd is invoked and it sets it as the "selected". When I don't pushObject a second time this private method isn't invoked (yet the item is in the selectbox and I can manually select it if I click into the dropdown again).

Any ideas why this isn't setting the selected (yet it's in the drop down?)

Thanks for the help!

**Comment by miguelcobain** [comment]
But to where you push those objects?
Can you show me some code?

**Comment by toranb** [comment]
```
    create:function(name) {
        var self = this
        var customer = { id: name, name: name };
        this.store.createRecord('customer', customer).save().then(function(persisted) {
            self.get('customers').pushObject(persisted);
            self.set('selectedCustomer', persisted);
```

**Comment by miguelcobain** [comment]
Looks good to me. And with that code the item doesn't get selected?

**Comment by toranb** [comment]
The template is not multi create -here it is (the customers property is an ember-data observable array Ember.A([]);

``` js
{{view Ember.Selectize
create="true" closeOnSelect="false"
contentBinding="customers"
selectionBinding="selectedCustomer"
optionValuePath="content.id"
optionLabelPath="content.name"
name="customer" id="customer"
placeholder="Select a customer"}}
```

**Comment by toranb** [comment]
Also -it works great when I'm not using the "create" feature. But after the promise (save) is resolved, ember-data does a pushObject w/ the same "persisted" record. If I pull out the pushObject I show above, it won't select the item in the selectbox

**Comment by toranb** [comment]
This version it will select it

this.store.createRecord('customer', customer).save().then(function(persisted) {
    self.get('customers').pushObject(persisted);
    self.set('selectedCustomer', persisted);
});

This will not select it

this.store.createRecord('customer', customer).save().then(function(persisted) {
    self.set('selectedCustomer', persisted);
});

The problem w/ the first one is that it creates "another" customer as I pushObject after ember-data does

**Comment by miguelcobain** [comment]
Why the hell would Ember-Data push the persisted object to `customers` array? o.O
How are you creating that array? In your route with ember-data?

**Comment by toranb** [comment]
That array is the object cache ember data tracks for me (so I call find or save without having to write a single line of network code). The array is pushed by my route and this drop down can think of it as an observable array ( updates like pushObject will add to it and update the dom with zero work like any normal ember array).

Could it be a timing issue? What special rules or logic exist in the adapter to set the "active item?

**Comment by toranb** [comment]
I ended up creating a copy of the ember data array just for this drop down -now I can keep it simple and do the pushObject + select and it's like the demo. Thanks for all the help!

**Comment by miguelcobain** [comment]
Well, obviously this issue has nothing to do with the tests. Still, I'm puzzled because I use Ember Data with Selectize all the time and never had that problem.
Just out of curiosity, how are you creating your Ember Data "magic array"?

Anyway, glad you were able to find a workaround, but I feel that solution isn't performance optimal.

**Comment by toranb** [comment]
Agreed on the performance issue -I'm actually evaluating another library / writing my own (low-tech) auto complete because in addition to the perf problem, my controller is a huge wreck now that I'm keeping 2 arrays in sync

If you use ember-data in depth, here is how the app works (my models look like this)

``` js
App.Customer = DS.Model.extend({
  name: attr('string'),
  appointments: hasMany('appointment', { async: true})
});

App.Appointment = DS.Model.extend({
  details: attr('string'),
  customer: belongsTo('customer', { async: true})
});
```

on boot, I use RSVP to fetch all the customer records

``` js
var customers = store.find('customer');
Ember.RSVP.all([customers]).then(function(results) {
  //at this point my ember-data store has all the customers
  App.advanceReadiness();
});
```

Next, when I visit this form's route, I push in all the customers into the controller like so

``` js
setupController: function(controller, model) {
  this._super(controller, {});
  controller.set('customers', this.store.all('customer'));
}
```

Then I bind this array to that property (the one set by the route above)

``` js
{{view Ember.Selectize
create="true"
contentBinding="customers"
selectionBinding="selectedCustomer"
optionValuePath="content.id"
optionLabelPath="content.name"
placeholder="Select a customer"}}
```

Next in the create, I save a new customer record and set the selected after the promise has resolved. At this point the ember inspector in chrome shows the record is already in the store (so the pushObject shouldn't be necessary). And if I select the dropdown the item is there, and I can select it (no issues).

``` js
var self = this;
var customer = { name: name };
return this.store.createRecord('customer', customer).save().then(function(persisted) {
  self.set('selectedCustomer', persisted);
}
```

**Comment by miguelcobain** [comment]
Ok, now I get it. I think its that `all` method that I never used.
I think the problem is that you're setting the `selectedCustomer` _before_ ember data pushes the object.
Never used Ember Data that way. :)

**Comment by toranb** [comment]
I thought it was timing related also, but even if I do a run later in the callback it will never set the "selected" correctly

``` js
var self = this;
var customer = { name: name };
return this.store.createRecord('customer', customer).save().then(function(persisted) {
  Ember.run.later(function() {
    self.set('selectedCustomer', persisted);
  }, 2000);
}
```
