### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by KeKs0r** [miguelcobain/ember-selectize#19]
Hi,

I was wondering for the source code of your example page on http://miguelcobain.github.io/ember-selectize/ but could not find it.

It would be great if your demo would also show some code in order to get a better understanding how to use ember-selectize.

**Comment by miguelcobain** [comment]
Hey.

Every github page has its source code on the `gh-pages` branch.
Please check https://github.com/miguelcobain/ember-selectize/tree/gh-pages for the source code of the demo.

Hope it helped!
