### ISSUE TITLE
Any way to speed up contentArrayDidChange function?

### ISSUE THREAD

**Issue by artburkart** [miguelcobain/ember-selectize#25]
If I use the regular selectize plugin without ember, I can set up a select with 500+ options and give it a default selected value and it will render instantaneously, however, if I do the same with ember-selectize, it takes about 1-3 seconds to render.

Here's the fix that I found:

``` js
  /*
   * Triggered after the content array changes
   * Here we process the inserted elements
   */
  contentArrayDidChange : function(array, idx, removedCount, addedCount) {
    // I added a check here so that I could massage the data into the format needed for addOption
    if (array && typeOf(array.objectAt(0)) === 'string') {
      var newArray = []
      for (var i = idx; i < idx + addedCount; i++) {
        var val = array.objectAt(i);
        newArray.push({value: val, label: val, data: val});
      }
      // All the calls made inside objectWasAdded have been hoisted up here
      this.selectize.addOption(newArray);
      this.selectize.refreshOptions(this.selectize.isFocused && !this.selectize.isInputHidden);
    } else {
      for (var i = idx; i < idx + addedCount; i++) {
        this.objectWasAdded(array.objectAt(i), i);
      }
    }
    this._selectionDidChange();
  },
```

Of course, this is just a quick hack and it only works when the options provided are all strings. Do you think the checks inside `objectWasAdded` could be moved up into `contentArrayDidChange` so that we could call `this.selectize.addOption` only once on the entire option array? Would that make a difference?

[Here's why](https://github.com/brianreavis/selectize.js/blob/f293d8b3100db2cc339d4b78ac3c9d0da53d431c/dist/js/standalone/selectize.js#L2154-2159) I think it's okay to pass the entire array at once to `this.selectize.addOption`

**Comment by artburkart** [comment]
I'm drawing up a PR for you. It seems a lot of the unit tests are broken, so I don't think I can be certain that my change won't break anything, but here's what I think the code should look like:

```
  contentArrayDidChange : function(array, idx, removedCount, addedCount) {
    var i, val, obj, newArray = [];
    if (this.selectize && array && array.length) {
      for (i = idx; i < idx + addedCount; i++) {
        obj = array.objectAt(i);
        if (typeOf(obj) === 'object' || typeOf(obj) === 'instance') {
          newArray.push({
            value: get(obj, get(this, '_valuePath')),
            label: get(obj, get(this, '_labelPath')),
            data: obj
          });
        } else {
          newArray.push({value: obj, label: obj, data: obj});
        }
      }
      this.selectize.addOption(newArray);
      this.selectize.refreshOptions(this.selectize.isFocused && !this.selectize.isInputHidden);
    }
  },
```

What do you think?

**Comment by miguelcobain** [comment]
Please try branch `iss25` and see if it works for you.

Basically I call `refreshOptions` **after** I add or remove all the options and not individually.
I believe this was what was slowing you down.

Let me know how it goes.
