### ISSUE TITLE
How to dynamically contentBinding

### ISSUE THREAD

**Issue by mblackritter** [miguelcobain/ember-selectize#28]
To dynamically create forms, we're trying to dynamically bind to a property defined in json, like:

``` handlebars
{{#each field in row.fields}}
    {{view Ember.Selectize id="country" contentBinding=field.property optionValuePath="content.code" optionLabelPath="content.name" selectionBinding="model.country" placeholder="Select country"}}
{{/each}}
```

This is my json:

``` javascript
{
  // ...
        fields: [
          {
            typeSelect: true,
            class: 'col-sm-6 col-md-6',
            label: 'Organisation Name',
            property: 'controllers.country.countries';
            placeholder: 'Country',
          }
        ]
  // ...
```

But this gives us just the string as the content.

We experienced issues with [Ember EasyForm](https://github.com/dockyard/ember-easyForm) too, which we also had to do some modifications to (), to achieve the desired outcome using dynamic bindings.

This seems to be a general issue within form extensions for Ember and/or Ember. But maybe we're just fundamentally missing something. ;)

The reason to generate forms dynamically is that we've a massive number of varying forms with repeating fields (E.g. first name, last name, street address, ...) and thereby in the next step ultimately want to be able to define each field type only once, so label, validation, placeholder, etc. are defined in one central json or maybe even Ember model.

Also being able to dynamically fetch forms from an API sounds like an interesting use case.

**Comment by miguelcobain** [comment]
Firstly, I believe that when you mention `json` you mean `javascript`?

Also, what is exactly the problem?

> But this gives us just the string as the content.

Which string?

Please explain your problem more precisely. Ideally set up a jsfiddle for us to help you.

Thanks!
