### ISSUE TITLE
Best way to update contents

### ISSUE THREAD

**Issue by rhinon** [miguelcobain/ember-selectize#30]
What is the best way to dynamically replace/update contents?  I've found that doing a set causes the current selections to be cleared.

For example (assuming someData is member of a controller:

``` handlebars
{{view Em.Selectize ... content=someData}}
```

and outside in a controller...

``` coffeescript
@set('someData', @get('newSetOfData'))
```

I find that this clears the current selections, I assume to observers treating this as emptying the content.

**Comment by miguelcobain** [comment]
Does `newSetOfData` include the current selection?

The only **valid** selections are those that are present in the content array. So, for instance you can't have a selection of `5` when your content array is `[1,2,3,4]`.

**Comment by miguelcobain** [comment]
Could you test how your code works with the regular `Ember.Select`?

I've been thinking about this. We need to know how Ember.Select works. I think it has the same principle, if i remember correctly.

**Comment by rhinon** [comment]
`newSetOfData` does indeed contain the selections.

I'll see what `Ember.Select` does, although I know it's somewhat neglected.  I believe it's something they've been meaning to update and cleanup (still extends View).

**Comment by miguelcobain** [comment]
A simple Jsbin illustrating the problem could help a lot to make sure we are talking about the same issue.
