### ISSUE TITLE
missing SortField option

### ISSUE THREAD

**Issue by popovevgeny** [miguelcobain/ember-selectize#34]
Hi!

Is it possible to add sortField option? There is a little bag in Google Chrome https://github.com/brianreavis/selectize.js/issues/198

**Comment by miguelcobain** [comment]
Hi.

Right now you can override the options that Ember.Selectize passes to Selectize.

``` javascript
Ember.Selectize.reopen({
  selectizeOptions:function(){
    var options = this._super();
    options.sortField = 'label';
    return options;
  }.property()
});
```

You can also subclass `Ember.Selectize` if you don't wish to do this for all instances.

Then use ember-selectize normally.

**Comment by popovevgeny** [comment]
thanks for quick answer!
