### ISSUE TITLE
bind placeholder/prompt to computed property

### ISSUE THREAD

**Issue by ashrafhasson** [miguelcobain/ember-selectize#35]
Hi there,
Binding the placeholder or the prompt to a computed property doesn't seem to update when the computed property changes. Is there a way to get this to work?

```
        {{view Ember.Selectize
            content=someProperty
            optionValuePath="content.value"
            optionLabelPath="content.label"
            selectionBinding="model"
            placeholder=computedProperty}}
```

**Comment by miguelcobain** [comment]
@ashrafhasson Check on master and please report any possible problems you may have with it.

**Comment by ashrafhasson** [comment]
works nicely, thanks!
