### ISSUE TITLE
Create Property not working...

### ISSUE THREAD

**Issue by jeather** [miguelcobain/ember-selectize#37]
So invoking the component for selectize.js with the option of `{create:true}` isn't working. .. . 

Here in my template I call:

```
 {{ember-selectize
  content=clients
  optionValuePath="content.id"
  optionLabelPath="content.name"
  selection=model.item
  sortField="text"
  create=true
  placeholder="Select an item"  id='client'}}
```

What I expect is when no options are available to the user, a "create new " option occurs. 

What am I missing here?

**Comment by miguelcobain** [comment]
@jeather, quoting the README from this repo:

> IMPORTANT
> Please use the new https://github.com/miguelcobain/ember-cli-selectize repository. This provides an Ember-cli addon and a standalone release. This repository will be unmaintained.

This repository is unmaintained. Is there any reason you want this version? You need a globals version?

**Comment by jeather** [comment]
My apologies - this issue should be in relation to the ember-cli-selectize repo - not this.

**Comment by miguelcobain** [comment]
Ah, ok!

Can you please open it there? Other people might help as well. :)
