### ISSUE TITLE
Where to write the user defined function for the select-item in ember-selectize?

### ISSUE THREAD

**Issue by mohangade118** [miguelcobain/ember-selectize#38]
Hi,
I am new to ember development. I have to call action on the ember-selectize, but I am not getting where to write that action code?

//template

{{ember-selectize
          id = property
          content = studentNames
          optionValuePath = "content.id"
          optionLabelPath = "content.name"
          placeholder = "Select a name"
          select-item=(action 'displayStudentName')
       }}
//Can we write the method displayStudentName in controller?

Thanks!

**Comment by miguelcobain** [comment]
If you're starting somthing, I advise you to use ember-power-select. That's the way to go.
