### ISSUE TITLE
Multiple selection - drawer doesn't show after one selection

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-selectize#6]
In multiple selection mode, when an item is selected, the drawer doesn't show again.
Needs focus out and a click.

**Comment by miguelcobain** [comment]
See demo at http://miguelcobain.github.io/ember-selectize/ for exemplification.

**Comment by miguelcobain** [comment]
I was being silly and closing the drawer `_onItemAdd`.

**Comment by rhinon** [comment]
Hello, it appears this fix was not merged into master.

**Comment by miguelcobain** [comment]
Oops. It has been fixed now. Thanks.
