### ISSUE TITLE
How to register an onclick / callback after selection

### ISSUE THREAD

**Issue by toranb** [miguelcobain/ember-selectize#8]
I'm looking through your tests and couldn't find a scenario where I can "select" an option, and based on that I can execute another action on my controller to "populate" another form field

Imagine this scenario:

I have a selectbox full of customers, when I select one I want to fill in the phone number field for this person just below the selectbox. How can I accomplish this today w/ this awesome library? If it's not possible today, I assume my other options include an observer of some kind that watches the property I set using my ValueBinding?

Thanks again for an awesome project !!!

**Comment by miguelcobain** [comment]
Correct me if I'm wrong, but I suspect that you're thinking too much "jquery way".

What you pass to the `selection` property will get updated with the currently selected item (or an array of items if multiple = true).
Then, in your template, I would just write `{{selectedCustomer.phoneNumber}}`. Please check the [demo page](http://miguelcobain.github.io/ember-selectize/) and see source code in the gh-pages branch. I believe it is something like that you need?

Am I missing something?

**Comment by toranb** [comment]
Ah excellent -the only "special" issue is that in some cases you "add a new customer" -in that case the phone number wouldn't be populated. In the "auto complete" case it would be (as you mention). How should I handle this scenario?

**Comment by miguelcobain** [comment]
I don't think that case is that special. It is a customer, but a new one.
`selectedCustomer.phoneNumber` would be empty or filled in, like any other customer.

See what I posted in issue #9 regarding item creation.

**Comment by toranb** [comment]
Excellent! I used the "selectedCustomer" and it worked perfectly !

One last question (again thanks for all the help). In the create, If I'm using the "create=true" option, but not the multiple how can I "set" the selectedCustomer in the add callback? I've implemented the create callback and see the object created, but when I try to set it like so ... it never adds it to the selectbox

``` js
actions: {
  create:function(name){
    var customer = Ember.Object.create({id: 999, name: name});
    this.set('selected', customer);
  }
}
```

Using your gh-pages branch I was able to simply remove the multiple=true part from the template, and then change the pushObject line to a simple set like this ... and it works so clearly I'm doing something wrong

``` js
  //this.get('selected').pushObject(obj);
  this.set('selected', obj);
```

**Comment by toranb** [comment]
Nevermind -it looks like I just needed to push it to both the array and set the selectedCustomer (like you did in the demo)

``` js
this.get('customers').pushObject(obj);
this.set('selected', obj);
```

**Comment by miguelcobain** [comment]
Exactly. The reason is simple: you can only select one or more items from the possible options, no other item is allowed.
You need to add it to the content property to inform selectize that this is now a possible option. Otherwise how would you distinguish valid from invalid selections?

Maybe in the future we can have some default behavior for create. Since this issue was closed, I assume that it is working for you now. :)

**Comment by toranb** [comment]
Yes -thank you, thank you, thank you! The only issue I"m fighting w/ on my personal project is that when I hit "tab" instead of "enter" during the create it doesn't seem to trigger as it does in your demo (Something I'll work through as your demo code works perfectly). Just a quick question -is the "tab" behavior something in your library or selectize itself (in this case) ?

thanks again for all your hard work on this awesome library !

**Comment by miguelcobain** [comment]
That behaviour is entirely delegated to Selectize. Both in the demo page and in my personal project, hitting tab works fine. It creates the item normally, just like hitting enter.
So it must be a problem with your code.

If you can provide a fiddle with an example of that happening, I could take a look.
