### ISSUE TITLE
How to support "add new" from the select?

### ISSUE THREAD

**Issue by toranb** [miguelcobain/ember-selectize#9]
Again looking through the tests, I couldn't find an example showing that w/ the default options you can support "adding" a new item to the select

For example, I search through my customer list and find that I don't yet have Axel Rose so I simply type the text "Axel Rose" and hit tab. I would like it to keep this text and let me keep that value but right now when I tab away it just defaults back to my placeholder.

How can I achieve this result w/ the ember-selectize library today?

**Comment by miguelcobain** [comment]
I have done some experimental integration with the tag creation and ajax loading.
I'll commit that today. :)

**Comment by toranb** [comment]
Excellent ! Thanks again for all your hardwork porting this library to ember. I found it yesterday and loved everything about it until I had to wire up the ember integration. But thanks to your library I get all that behavior w/out having to write a single line of code +1

**Comment by miguelcobain** [comment]
Actually, I didn't port anything. Selectize is absolutely intact! I just wrote this glue code between both.
That's the beauty of ember. :)

Thanks.

**Comment by toranb** [comment]
Just to clarify -the tagging is awesome but is there a chance you could also support this feature of selectize (add from the normal dropdown without tagging)

![screen shot 2014-01-23 at 8 53 36 am](https://f.cloud.github.com/assets/147411/1985448/505c5bb4-843e-11e3-9a34-5bf7ff4fe538.png)

**Comment by miguelcobain** [comment]
@toranb See the referenced commit. I've added support for this along with some tests.

Tag creation is the same thing you mentioned. Just that tag creation is usually used for multiple selections. But its the same thing! As far as I know, Selectize only support one kind of creation.

Basically, now you can tell ember-selectize to send an action to its controller when the user creates a tag.

Be aware that **_the tag will be discarded from the selectize side**_. This means that _your action_ will be responsible for creating and adding the new object to the content array. As usual, Selectize will reflect the changes. :)

---

### Example with default 'create' action

Template:

```
{{view App.Select2 contentBinding="allCustomers" selectionBinding="customers"
   multiple="true" closeOnSelect="false" optionValuePath="content.value" optionLabelPath="content.name"
   create="true"}}
```

Controller:

```
   //...
   actions:{
      create:function(input){
         //do whatever you want with the input
         //you should create an object and add it to allCustomers
         //otherwise it won't show up in Selectize
      }
   }
```

### Example with custom named action

This is useful if you have several select boxes in the same template which require creation.

Template:

```
{{view App.Select2 contentBinding="allCustomers" selectionBinding="customers"
   multiple="true" closeOnSelect="false" optionValuePath="content.value" optionLabelPath="content.name"
   createAction="createCustomer"}}
{{view App.Select2 contentBinding="allProducts" selectionBinding="products"
   multiple="true" closeOnSelect="false" optionValuePath="content.value" optionLabelPath="content.name"
   createAction="createProduct"}}
```

Controller:

```
   //...
   actions:{
      createCustomer:function(input){
         //do whatever you want with the input
         //you should create an object and add it to allCustomers
      },
      createProduct:function(input){
         //do whatever you want with the input
         //you should create an object and add it to allProducts
      }
   }
```

Also, the usual action bubbling from ember still applies. You could write these actions in any of your routes as well.

Is this what you were looking for?

**Comment by toranb** [comment]
Wow -this is what I call above and beyond! thanks again (saving me some real effort on a commercial project I'm shipping -your work has made a big impact !!!)

**Comment by miguelcobain** [comment]
I just updated the [demo page](http://miguelcobain.github.io/ember-selectize/) with an item creation example in action. You can see its source. It is really simple.

Glad I helped. :)

Closing this issue.
